// L5 — Controlled GHL submission tests via Preview API
// Uses obviously fake test data marked "L5QA-" so user can identify + clean up.
//
// USAGE:
//   1. Sawil enables HIGHLEVEL_TOKEN + HIGHLEVEL_LOCATION_ID for Preview scope.
//   2. Sawil redeploys Preview and shares the new URL (or the existing one if reused).
//   3. Update PREVIEW_BASE and SHARE_TOKEN below if changed.
//   4. node test-L5-api.mjs
//
// SECURITY: Logs cookie NAMES only (never values). No GHL tokens read or printed.

import { writeFileSync } from 'node:fs';

const PREVIEW_BASE = 'https://clearpoint-deploy-h5ly6xs85-sawil-reyess-projects.vercel.app';
const ENDPOINT = `${PREVIEW_BASE}/api/submit-lead`;
const SHARE_TOKEN = 'dlyrOcILfDoNlt8YN4AWQ5rTTiByYTqF'; // Vercel SSO bypass (23-hr lifetime; refresh via get_access_to_vercel_url if expired)
const SHARE_URL = `${PREVIEW_BASE}/?_vercel_share=${SHARE_TOKEN}`;

// ── Warmup: visit share URL, follow redirects, capture _vercel_jwt cookie ──
let cookieJar = '';
async function warmup() {
  let url = SHARE_URL;
  for (let i = 0; i < 5; i++) {
    const res = await fetch(url, {
      method: 'GET',
      redirect: 'manual',
      headers: cookieJar ? { Cookie: cookieJar } : {},
    });
    const setCookies = res.headers.getSetCookie ? res.headers.getSetCookie() : [];
    if (setCookies.length) {
      const map = new Map(cookieJar ? cookieJar.split('; ').map(p => p.split('=').slice(0, 2)).filter(a => a[0]).map(([k, v]) => [k, v]) : []);
      for (const c of setCookies) {
        const [k, v] = c.split(';')[0].split('=');
        if (k) map.set(k, v ?? '');
      }
      cookieJar = [...map.entries()].map(([k, v]) => `${k}=${v}`).join('; ');
    }
    const loc = res.headers.get('location');
    if (res.status >= 300 && res.status < 400 && loc) {
      url = loc.startsWith('http') ? loc : new URL(loc, url).toString();
      continue;
    }
    break;
  }
  const names = cookieJar.split('; ').map(c => c.split('=')[0]).filter(Boolean);
  console.log(`Warmup cookies acquired: ${names.length ? names.join(', ') : '(none)'}\n`);
}

async function callAPI(payload, testId) {
  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': cookieJar,
    },
    body: JSON.stringify(payload),
    redirect: 'manual',
  });
  const text = await res.text();
  let json = null;
  try { json = JSON.parse(text); } catch {}
  return {
    testId,
    status: res.status,
    ok: res.ok,
    response: json,
    rawText: json ? null : text.slice(0, 500),
    payload, // recorded for log file
  };
}

const ts = new Date().toISOString();
await warmup();

// ── TEST 0 — Preflight ──
console.log('=== TEST 0 — Preflight: env vars configured for Preview? ===');
const t0 = await callAPI({}, 'T0-preflight');
console.log(`Status: ${t0.status} | Response: ${JSON.stringify(t0.response || t0.rawText).slice(0, 200)}`);
const T0_BLOCKED = t0.status === 500 && t0.response?.error && /configuration/i.test(t0.response.error);
if (T0_BLOCKED) {
  console.log('❌ BLOCKED: HIGHLEVEL_TOKEN or HIGHLEVEL_LOCATION_ID not configured for Preview environment.');
  console.log('   Cannot proceed with live submission tests.');
  writeFileSync('L5-test-results.json', JSON.stringify({ blocked: true, t0 }, null, 2));
  process.exit(0);
}
console.log('✅ Env vars appear configured — API rejects empty payload at validation layer, not env layer\n');

// ── TEST 5 — Validation failure (bad phone) ──
console.log('=== TEST 5 — Validation failure: bad phone (no real contact created) ===');
const t5 = await callAPI({
  first_name: 'L5QA-BadPhone',
  phone: '0000000000',
  consent_to_contact: true,
}, 'T5-validation');
console.log(`Status: ${t5.status} | Response: ${JSON.stringify(t5.response || t5.rawText).slice(0, 200)}`);
console.log(`  → Expected 400. Got: ${t5.status} ${t5.status === 400 ? 'PASS (validation working)' : 'FAIL'}\n`);

// ── TEST 1 — English Smart Review ──
console.log('=== TEST 1 — English Smart Review — creates real GHL contact (L5QA marker) ===');
const t1 = await callAPI({
  first_name: 'L5QA-English',
  last_name: 'TestEnglish',
  phone: '2125550100',
  email: 'l5qa-en@example.invalid',
  preferred_language: 'en',
  zip: '10001',
  city: 'New York',
  county: 'New York',
  derived_state: 'NY',
  state: 'NY',
  date_of_birth: '01/15/1955',
  calculated_age: 70,
  medicare_status: 'Original Medicare (Parts A & B)',
  interest_type: 'I want to review or change my current plan',
  consent_to_contact: true,
  consent: true,
  consent_sms: true,
  consent_call: true,
  lead_notes: '[L5 QA TEST — Safe to delete] English Smart Review path. Lead generated by Claude L5 verification.',
  conversation_summary: 'L5 QA TEST. Language: English. State: NY. ZIP: 10001. Concern: review current plan. Source: SmartReview.',
  lead_source: 'Smart Medicare Review',
  form_name: 'Smart Medicare Review',
  tags: ['Smart Review Lead', 'Medicare Lead', 'English'],
  created_at: ts,
}, 'T1-EN-SmartReview');
console.log(`Status: ${t1.status} | contactId: ${t1.response?.contact_id || 'N/A'}`);
console.log(`  Response: ${JSON.stringify(t1.response).slice(0, 300)}\n`);

// ── TEST 2 — Spanish Smart Review (FL) ──
console.log('=== TEST 2 — Spanish Smart Review (FL) — creates real GHL contact (L5QA marker) ===');
const t2 = await callAPI({
  first_name: 'L5QA-Spanish',
  last_name: 'TestSpanish',
  phone: '3055550100',
  email: 'l5qa-es@example.invalid',
  preferred_language: 'es',
  zip: '33101',
  city: 'Miami',
  county: 'Miami-Dade',
  derived_state: 'FL',
  state: 'FL',
  date_of_birth: '03/20/1958',
  calculated_age: 67,
  medicare_status: 'Medicare Advantage',
  interest_type: 'Quiero reducir mis costos de Medicare',
  consent_to_contact: true,
  consent: true,
  consent_sms: true,
  consent_call: true,
  lead_notes: '[L5 QA TEST — Safe to delete] Spanish Smart Review path. Lead generated by Claude L5 verification.',
  conversation_summary: 'L5 QA TEST. Idioma: Espanol. Estado: FL. ZIP: 33101. Concern: lower Medicare costs. Source: SmartReview.',
  lead_source: 'Smart Medicare Review',
  form_name: 'Smart Medicare Review',
  tags: ['Smart Review Lead', 'Medicare Lead', 'Spanish'],
  created_at: ts,
}, 'T2-ES-SmartReview');
console.log(`Status: ${t2.status} | contactId: ${t2.response?.contact_id || 'N/A'}`);
console.log(`  Response: ${JSON.stringify(t2.response).slice(0, 300)}\n`);

// ── TEST 3 — Special-care red-flag ──
console.log('=== TEST 3 — Special-care red-flag — creates real GHL contact (L5QA marker) ===');
const t3 = await callAPI({
  first_name: 'L5QA-SpecialCare',
  last_name: 'TestSpecialCare',
  phone: '2125550101',
  email: 'l5qa-sc@example.invalid',
  preferred_language: 'en',
  zip: '10001',
  city: 'New York',
  county: 'New York',
  derived_state: 'NY',
  state: 'NY',
  date_of_birth: '06/10/1950',
  calculated_age: 75,
  medicare_status: 'Original Medicare (Parts A & B)',
  interest_type: 'I receive home care, nursing home care, PACE, MAP, LTC, I-SNP, or special care support',
  consent_to_contact: true,
  consent: true,
  consent_sms: true,
  consent_call: true,
  lead_notes: '[L5 QA TEST — Safe to delete] Special-care red-flag path. CAREFUL REVIEW REQUIRED — licensed advisor must verify benefits before any plan change. Lead generated by Claude L5 verification.',
  conversation_summary: 'L5 QA TEST — SpecialCare path. Language: English. State: NY. Concern: home care / PACE / MAP / LTC / I-SNP — RED FLAG.',
  lead_source: 'Smart Medicare Review',
  form_name: 'Smart Medicare Review',
  tags: ['Smart Review Lead', 'Medicare Lead', 'English', 'Alert SpecialCare'],
  lead_quality_flags: 'Special care situation — careful licensed advisor review required',
  created_at: ts,
}, 'T3-SpecialCare');
console.log(`Status: ${t3.status} | contactId: ${t3.response?.contact_id || 'N/A'}`);
console.log(`  Response: ${JSON.stringify(t3.response).slice(0, 300)}\n`);

// ── TEST 4 — Free Review LeadForm path ──
console.log('=== TEST 4 — Free Review / LeadForm path — creates real GHL contact (L5QA marker) ===');
const t4 = await callAPI({
  first_name: 'L5QA-FreeReview',
  last_name: 'TestFreeReview',
  phone: '6465550100',
  email: 'l5qa-fr@example.invalid',
  preferred_language: 'en',
  zip: '10001',
  city: 'New York',
  county: 'New York',
  derived_state: 'NY',
  state: 'NY',
  medicare_status: 'Medicare Advantage',
  consent_to_contact: true,
  consent: true,
  consent_sms: true,
  consent_call: true,
  lead_notes: '[L5 QA TEST — Safe to delete] Free Review / LeadForm path. Source: contact-page Form. Status: Medicare Advantage. Lead generated by Claude L5 verification.',
  conversation_summary: '',
  lead_source: 'ClearPoint Senior Advisors Website',
  form_name: 'contact-page Form',
  tags: ['Website Lead', 'Medicare Lead', 'ClearPoint Website', 'Form Lead', 'Consent Captured', 'English'],
  created_at: ts,
}, 'T4-FreeReview');
console.log(`Status: ${t4.status} | contactId: ${t4.response?.contact_id || 'N/A'}`);
console.log(`  Response: ${JSON.stringify(t4.response).slice(0, 300)}\n`);

// ── Summary ──
console.log('=== L5 PHASE 7 SUMMARY ===');
const tests = [
  { id: 'T0', name: 'Preflight env vars', expected: 'NOT 500', actual: t0.status, pass: t0.status !== 500 },
  { id: 'T5', name: 'Validation failure (bad phone)', expected: '400', actual: t5.status, pass: t5.status === 400 },
  { id: 'T1', name: 'EN Smart Review NY → GHL contact', expected: '200', actual: t1.status, pass: t1.status === 200 && !!t1.response?.contact_id },
  { id: 'T2', name: 'ES Smart Review FL → GHL contact', expected: '200', actual: t2.status, pass: t2.status === 200 && !!t2.response?.contact_id },
  { id: 'T3', name: 'Special-care red-flag → GHL contact', expected: '200', actual: t3.status, pass: t3.status === 200 && !!t3.response?.contact_id },
  { id: 'T4', name: 'Free Review LeadForm → GHL contact', expected: '200', actual: t4.status, pass: t4.status === 200 && !!t4.response?.contact_id },
];
tests.forEach(t => console.log(`  ${t.pass ? 'PASS' : 'FAIL'} | ${t.id} | ${t.name} | expected ${t.expected}, got ${t.actual}`));
console.log('\nContact IDs created (L5QA marker, safe to delete):');
[t1, t2, t3, t4].forEach((t, i) => {
  const cid = t.response?.contact_id;
  if (cid) console.log(`  T${i+1}: ${cid}`);
});

// ── Write structured log file for verification ──
const logPath = 'L5-test-results.json';
writeFileSync(logPath, JSON.stringify({
  timestamp: ts,
  endpoint: ENDPOINT,
  cookies_used: cookieJar.split('; ').map(c => c.split('=')[0]),
  summary: tests,
  tests: { t0, t5, t1, t2, t3, t4 },
  contact_ids: [t1, t2, t3, t4].map(t => t.response?.contact_id).filter(Boolean),
}, null, 2));
console.log(`\nFull results written to: ${logPath}`);
