// AUDIT 2026-07-03 (perf) — WebP-with-fallback image.
//
// Serves the WebP variant (generated by scripts/webp-convert.mjs, ~32% smaller)
// to modern browsers and falls back to the original JPG for old Safari/iOS.
// Drop-in for a plain <img src="/foo.jpg">: same visual output, smaller payload.
// The webp path is derived from the jpg path, so every public/*.jpg that has a
// matching *.webp is upgraded automatically; anything without a .webp still
// renders via the <img> fallback (no broken image).

import type { ImgHTMLAttributes } from 'react';

interface PictureImgProps extends ImgHTMLAttributes<HTMLImageElement> {
  src: string;
}

export function PictureImg({ src, className, ...imgProps }: PictureImgProps) {
  const webp = /\.(jpe?g)$/i.test(src) ? src.replace(/\.(jpe?g)$/i, '.webp') : null;
  // `display: contents` makes <picture> generate NO layout box, so the inner
  // <img>'s sizing classes (w-full/h-full/object-cover/absolute-fill) resolve
  // against the ORIGINAL parent container exactly as a bare <img> did — no layout
  // change. Without this, <picture>'s default `display:inline` shrinks to content
  // and the hero background stops covering. Supported in Safari 11.1+ / iOS 14.
  return (
    <picture style={{ display: 'contents' }}>
      {webp && <source srcSet={webp} type="image/webp" />}
      <img src={src} className={className} {...imgProps} />
    </picture>
  );
}
